//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavPortali
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevaplar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cevaplar()
        {
            this.resimler = new HashSet<resimler>();
        }
    
        public int id { get; set; }
        public int KTG_id { get; set; }
        public int soruID { get; set; }
        public string cevap { get; set; }
        public string cevapDokuman { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
        public virtual sorular sorular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resimler> resimler { get; set; }
    }
}
