//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavPortali
{
    using System;
    using System.Collections.Generic;
    
    public partial class degerlendirme
    {
        public int id { get; set; }
        public int katId { get; set; }
        public int kullanici_id { get; set; }
        public int puan { get; set; }
        public string yorum { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
