//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavPortali
{
    using System;
    using System.Collections.Generic;
    
    public partial class girisler
    {
        public int id { get; set; }
        public int kid { get; set; }
        public string kullanici_adi { get; set; }
        public string parola { get; set; }
        public string durum { get; set; }
    
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
