//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavPortali
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici_cevaplar
    {
        public int id { get; set; }
        public int klnc_id { get; set; }
        public int KTGID { get; set; }
        public int soruid { get; set; }
        public string klnc_cevap { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
        public virtual sorular sorular { get; set; }
    }
}
