//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavPortali
{
    using System;
    using System.Collections.Generic;
    
    public partial class resimler
    {
        public int id { get; set; }
        public int KTG_ID { get; set; }
        public int srd_id { get; set; }
        public int cvp_id { get; set; }
        public string soruResim { get; set; }
    
        public virtual cevaplar cevaplar { get; set; }
        public virtual kategoriler kategoriler { get; set; }
        public virtual resimler resimler1 { get; set; }
        public virtual resimler resimler2 { get; set; }
        public virtual sorular sorular { get; set; }
    }
}
