//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavPortali
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinavIstatistik
    {
        public int id { get; set; }
        public int Kullanici_ID { get; set; }
        public int KAT_ID { get; set; }
        public Nullable<int> dogruSay { get; set; }
        public Nullable<int> yanlisSay { get; set; }
        public Nullable<int> puan { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
        public virtual kullanicilar kullanicilar { get; set; }
    }
}
